CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  user_name VARCHAR(50) NOT NULL UNIQUE 
    CHECK (REGEXP_LIKE(user_name, '^[A-Za-z0-9]+$') AND (user_name >= 2 AND user_name <= 50)),
  password VARCHAR(20) NOT NULL UNIQUE CHECK ( password >= 8 AND password <= 20),
  admin_role VARCHAR(10) DEFAULT 'user' NOT NULL 
    CHECK (admin_role in ('user','admin')) 
  ); --Complete Constraints: YES

CREATE TABLE homeowners (
  user_id INT NOT NULL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  dob DATE NOT NULL,
  retired_status NUMBER(1,0) NOT NULL,
  ssn VARCHAR(9)NOT NULL,
  email VARCHAR(50) NOT NULL,
    CONSTRAINT fk_users_homeowners
      FOREIGN KEY (user_id)
      REFERENCES users(user_id) 
  ); --Complete Constraints: NO
  
CREATE TABLE locations (
  location_id INT PRIMARY KEY,
  user_id INT NOT NULL,
  residence_type VARCHAR(25) NOT NULL,
  address_line_1 VARCHAR(50) NOT NULL,
  address_line_2 VARCHAR(50),
  city VARCHAR(25) NOT NULL,
  location_state VARCHAR(25) NOT NULL,
  zip_code VARCHAR(9) NOT NULL,
  residence_use VARCHAR(20) NOT NULL,
    CONSTRAINT fk_users_locations
      FOREIGN KEY (user_id)
      REFERENCES users(user_id)   
); --Complete Constraints: NO

CREATE TABLE properties (
  location_id INT PRIMARY KEY,
  market_value FLOAT(2) NOT NULL,
  year_built INT NOT NULL,
  square_footage INT NOT NULL,
  dwelling_type VARCHAR(10) NOT NULL,
  "roof-material" VARCHAR(10) NOT NULL,
  garage_type VARCHAR(15) NOT NULL,
  full_baths INT NOT NULL,
  half_baths INT NOT NULL,
  pool NUMBER(1,0) NOT NULL,
    CONSTRAINTS fk_locations_properties
      FOREIGN KEY (location_id)
      REFERENCES locations(location_id)      
  ); --Complete Constraints: No
  
CREATE TABLE quotes (
  quote_id INT PRIMARY KEY,
  location_id INT UNIQUE,
  monthly_premium FLOAT(2) NOT NULL,
  dwelling_coverage FLOAT(2) NOT NULL,
  detached_structures FLOAT(2) NOT NULL,
  personal_property FLOAT(2) NOT NULL,
  add_living_exp FLOAT(2) NOT NULL,
  medical_expense FLOAT(2) NOT NULL,
  deductible FLOAT(2) NOT NULL,
    CONSTRAINTS fk_locations_quotes
      FOREIGN KEY (location_id)
      REFERENCES locations(location_id)
  ); --Complete Constraints: No
  
CREATE TABLE policies (
  policy_id INT PRIMARY KEY,
  quote_id INT UNIQUE,
  user_id INT,
  effective_date DATE,
  end_date DATE,
  term INT NOT NULL,
  policy_status VARCHAR(10) NOT NULL,
    CONSTRAINTS fk_users_policies
      FOREIGN KEY (user_id)
      REFERENCES users(user_id),
    CONSTRAINTS fk_quotes_policies
      FOREIGN KEY (quote_id)
      REFERENCES quotes(quote_id)   
); --Complete Constraints: No
  
  
  
